repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest before committing
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]